### ISSUE TITLE
Plugin doesn't work with Android Studio 0.5.1

### ISSUE THREAD

**Issue by jdreesen** [square/dagger-intellij-plugin#10]
I get this error when klicking on one of the icons.

```
com.intellij.find.findUsages.FindUsagesManager.startProcessUsages(Lcom/intellij/find/findUsages/FindUsagesHandler;Lcom/intellij/usages/UsageInfoToUsageConverter$TargetElementsDescriptor;Lcom/intellij/util/Processor;Lcom/intellij/find/findUsages/FindUsagesOptions;Ljava/lang/Runnable;)Lcom/intellij/openapi/progress/ProgressIndicator;: com.intellij.find.findUsages.FindUsagesManager.startProcessUsages(Lcom/intellij/find/findUsages/FindUsagesHandler;Lcom/intellij/usages/UsageInfoToUsageConverter$TargetElementsDescriptor;Lcom/intellij/util/Processor;Lcom/intellij/find/findUsages/FindUsagesOptions;Ljava/lang/Runnable;)Lcom/intellij/openapi/progress/ProgressIndicator;
java.lang.NoSuchMethodError: com.intellij.find.findUsages.FindUsagesManager.startProcessUsages(Lcom/intellij/find/findUsages/FindUsagesHandler;Lcom/intellij/usages/UsageInfoToUsageConverter$TargetElementsDescriptor;Lcom/intellij/util/Processor;Lcom/intellij/find/findUsages/FindUsagesOptions;Ljava/lang/Runnable;)Lcom/intellij/openapi/progress/ProgressIndicator;
    at com.squareup.ideaplugin.dagger.ShowUsagesAction.showElementUsages(ShowUsagesAction.java:428)
    at com.squareup.ideaplugin.dagger.ShowUsagesAction.startFindUsages(ShowUsagesAction.java:276)
    at com.squareup.ideaplugin.dagger.handler.ConstructorInjectToProvidesHandler.showUsages(ConstructorInjectToProvidesHandler.java:48)
    at com.squareup.ideaplugin.dagger.handler.ConstructorInjectToProvidesHandler.navigate(ConstructorInjectToProvidesHandler.java:36)
    at com.intellij.codeInsight.daemon.LineMarkerInfo$NavigateAction.actionPerformed(LineMarkerInfo.java:123)
    at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.mouseReleased(EditorGutterComponentImpl.java:1230)
    at com.intellij.openapi.editor.impl.EditorImpl.processMouseReleased(EditorImpl.java:3986)
    at com.intellij.openapi.editor.impl.EditorImpl.access$10900(EditorImpl.java:135)
    at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter$2.run(EditorImpl.java:5541)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
    at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseReleasedCommand(EditorImpl.java:5544)
    at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:5437)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
    at java.awt.Component.processMouseEvent(Component.java:6505)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:682)
    at java.awt.EventQueue$3.run(EventQueue.java:680)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:696)
    at java.awt.EventQueue$4.run(EventQueue.java:694)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:693)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:520)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)
```
